GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-type: application/json

{
 "author":"yo",
"url":"himalayan.com", 
"title":"scrapping all post of ravi", 
"likes":203  
}

###
DELETE http://localhost:3001/api/blogs/7

###
PUT  http://localhost:3001/api/blogs/2
Content-type: application/json


{
    "likes":22
}