GET http://localhost:3002/api/blogs

###

POST http://localhost:3002/api/blogs
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaXJkIiwiaWQiOjMsImlhdCI6MTY3NjM2OTg2MH0.9jr6raEm9SAeJfVHThV7BzTOdeIOHhJoMl9w-AxOrHM

{
 "author":"third3",
"url":"setopati.com", 
"title":"pokhara", 
"likes": 30,
"year":"2000"
}

###
DELETE http://localhost:3002/api/blogs/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpcnN0IiwiaWQiOjUsImlhdCI6MTY3NTkxNDgxMH0.CUghPePnodv2W95cO4HEntIaTfMTzIOhM6-p71rmfnY

###
PUT  http://localhost:3002/api/blogs/2
Content-type: application/json


{
    "likes":22
}

###
POST http://localhost:3002/api/users
Content-type: application/json

{
"username": "third",
"name":"third",
"password":"password"

}
 
###
POST http://localhost:3002/api/login
Content-type: application/json

{
"username": "second",
"password":"password"

}

###
GET http://localhost:3002/api/users

###
PUT  http://localhost:3002/api/users/
Content-type: application/json


{
    "likes":22
}

###
PUT  http://localhost:3002/api/users/shinido
Content-type: application/json

{
    "username":"ShinidOOO"
}


###

POST http://localhost:3002/api/reading
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZCIsImlkIjoyLCJpYXQiOjE2NzY2MjUxNzl9.pBfTzM4mIKl8JG9OLeu-cUP4yZxWkZ6BVRlfTeMRyoc

{
 "blogId":"5",
"userId":"2",
"isRead": true
}

###
PUT  http://localhost:3002/api/reading/12
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZCIsImlkIjoyLCJpYXQiOjE2NzY2MjUxNzl9.pBfTzM4mIKl8JG9OLeu-cUP4yZxWkZ6BVRlfTeMRyoc


{
    "isRead":true
}

###
DELETE  http://localhost:3002/api/reading/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpcnN0IiwiaWQiOjEsImlhdCI6MTY3NjM3MjkwNn0.pRWqaKAo0VG-dqLI9YheSrAqfwoolPjmBT9tai7wwXE

